config:
  app:
    host: 0.0.0.0
    port: 8000
    reload: true

  logging:
    level: INFO
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    filename: "logs/app.log"
    filemode: "a"
    maxBytes: 1048576
    backupCount: 3